name: iOS Automation Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install project dependencies
        run: npm install

      - name: Install Appium
        run: npm install -g appium@3.0.0-rc.2

      - name: Install XCUITest driver
        run: appium driver install xcuitest

      - name: Download iOS app
        run: |
          mkdir -p apps
          curl -L -o apps/MyDemoApp.zip "https://github.com/saucelabs/my-demo-app-ios/releases/download/2.2.2/SauceLabs-Demo-App.Simulator.zip"
          unzip apps/MyDemoApp.zip -d apps/

      - name: Boot iOS Simulator
        run: |
            xcrun simctl boot "iPhone 15" || true
            xcrun simctl list devices | grep Booted

      - name: Start Appium server
        run: appium &

      - name: Wait for Appium to start
        run: sleep 15

      - name: Run automation tests
        run: npx wdio run wdio.conf.ci.js